version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    ports:
      - "27017:27017"
    volumes:
      - user_secrets:/run/secrets
    entrypoint: ["/bin/sh", "-c", "cat /run/secrets/mongo_user > /tmp/mongo_user && cat /run/secrets/mongo_password > /tmp/mongo_password && exec docker-entrypoint.sh mongod"]

  web:
    build: .
    container_name: aspnet_docker_app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - user_secrets:/root/.microsoft/usersecrets

volumes:
  user_secrets:
