version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo1337
      MONGO_INITDB_DATABASE: devopsplaces

  api:
    build: .
    container_name: places-api
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/Devops.Places.Api/appsettings.json:/app/appsettings.json:ro
